made auton delay
LakotaRobotics1038/2024RobotProject pull request #124
Opened 2024-03-13 21:56 UTC by Griffin9881

### Pull Request

---------------------------------------------

#### Issue Number

Closes #74 

#### Comments

2024-03-13 22:20 UTC, reediculous456 requested changes
Did you see the code that I pushed? I think it will be a lot easier to work with from a DS standpoint and be more flexible

2024-03-13 23:09 UTC, Griffin9881 commented
where did you push that code?

2024-03-13 23:20 UTC, reediculous456 commented
https://github.com/LakotaRobotics1038/2024RobotProject/tree/auton-delay

2024-03-13 23:29 UTC, Griffin9881 commented
I feel like a dropdown would be fine since you wouldn't really have a situation where you needed to be more accurate than that

2024-03-13 23:33 UTC, reediculous456 commented
Interesting, I would expect that to work

2024-03-13 23:34 UTC, Griffin9881 commented
me too

2024-03-13 23:35 UTC, reediculous456 commented
Does my branch work? I have a theory

2024-03-14 00:08 UTC, Griffin9881 commented
both branches work now because i guess it had to be in the auton class, I would prefer to use my code because I think it would be easier than using a text box and also it was made by a student

2024-03-14 00:39 UTC, reediculous456 commented
Ok. One thing you could do to reduce the overhead here is remove the enum and just assign the seconds straight to the options in the chooser. The only reason we don’t do that for autons is because we need to construct the auton in auto init not on robot init

2024-03-14 21:29 UTC, matunkar submitted a review, later dismissed

2024-03-14 21:47 UTC, reediculous456 requested changes

2024-03-14 21:47 UTC, reediculous456 commented on src/main/java/frc/robot/autons/AutonSelector.java
> +    SendableChooser<String> delayChooser;
```suggestion
    SendableChooser<double> delayChooser;
```
If you do this you don’t need the switch statement. You can just return the get value from the chooser

2024-03-16 19:22 UTC, reediculous456 approved these changes

2024-03-16 19:44 UTC, merged