TWO lift commands (one to depress one to elevate)
LakotaRobotics1038/2024RobotProject pull request #18
Opened 2024-01-13 19:01 UTC by matunkar

### Pull Request

---------------------------------------------

#### Issue Number

#### Comments

created two command skeletons, one to depress the lift elevator and one to raise it.

2024-01-13 19:11 UTC, Saum27 approved these changes

2024-01-15 14:17 UTC, reediculous456 requested changes

2024-01-15 14:17 UTC, reediculous456 commented on src/main/java/frc/robot/commands/LiftElevateCommand.java
> +public class LiftElevateCommand extends Command {
```suggestion
public class LiftExtendCommand extends Command {
```

2024-01-15 22:37 UTC, reediculous456 approved these changes

2024-01-15 22:37 UTC, merged