i did theStorage Run Command Skeleton
LakotaRobotics1038/2024RobotProject pull request #19
Opened 2024-01-13 19:43 UTC by Gaviniscool17

### Pull Request

---------------------------------------------

#### Issue Number

Closes #13

#### Comments

I made the skeleton for the storage run command

2024-01-13 19:46 UTC, Saum27 approved these changes

2024-01-13 19:47 UTC, matunkar approved these changes

2024-01-15 14:02 UTC, reediculous456 requested changes

2024-01-15 14:02 UTC, reediculous456 commented on src/main/java/frc/robot/commands/StorageRunCommand.java
> +import frc.robot.subsystems.Scoring;
Don't import scoring if it's not being used

2024-01-15 14:02 UTC, reediculous456 commented on src/main/java/frc/robot/commands/StorageRunCommand.java
> +    public void initialize() {
Remove this function since it's empty

2024-01-15 22:40 UTC, reediculous456 requested changes

2024-01-15 22:40 UTC, reediculous456 commented on src/main/java/frc/robot/subsystems/Storage.java
> -        storageMotor.set(StorageConstants.motorSpeed);
I'll leave this up to @matunkar as the controls lead, but either this needs put back and storage always runs at a constant speed OR the input speed needs to be clamped to a min and max value before being set

2024-01-16 00:29 UTC, reediculous456 requested changes

2024-01-16 00:29 UTC, reediculous456 commented on src/main/java/frc/robot/subsystems/Storage.java
> -        storageMotor.set(StorageConstants.motorSpeed);
Thinking about how storage usually works, I believe this should be put back. Storage usually runs forward or backward at a constant speed in order to feed into acquisition consistently

2024-01-16 23:39 UTC, reediculous456 commented
My comments have not been addressed

2024-01-18 21:51 UTC, merged