sensors added :D
LakotaRobotics1038/2024RobotProject pull request #46
Opened 2024-01-30 00:21 UTC by matunkar

### Pull Request

---------------------------------------------

#### Issue Number

Closes #44

#### Comments

2024-01-30 00:33 UTC, Murat65536 requested changes

2024-01-30 00:33 UTC, Murat65536 commented on src/main/java/frc/robot/subsystems/Acquisition.java
> +
You are not returning anything. Add "void".

2024-01-31 00:11 UTC, Griffin9881 approved these changes
looks pretty adequate

2024-01-31 22:49 UTC, reediculous456 requested changes

2024-01-31 22:49 UTC, reediculous456 commented on src/main/java/frc/robot/subsystems/Acquisition.java
> +    public boolean getLaserOutput() {
```suggestion
    public boolean isNotePresent() {
```

2024-01-31 22:49 UTC, reediculous456 commented on src/main/java/frc/robot/subsystems/Scoring.java
> +    public boolean getLaserOutput() {
```suggestion
    public boolean isNotePresent() {
```

2024-01-31 22:49 UTC, reediculous456 commented on src/main/java/frc/robot/subsystems/Storage.java
> +    public boolean getLaserOutput() {
```suggestion
    public boolean isNotePresent() {
```

2024-01-31 22:49 UTC, reediculous456 commented on src/main/java/frc/robot/subsystems/Scoring.java
> +    private static DigitalInput loaderLaser = new DigitalInput(ScoringConstants.loaderLaserPort);
This laser should be in the storage subsystem. I recommend calling them transitionLaser and storageSensor

2024-02-03 19:48 UTC, reediculous456 commented
Being completed by #64

2024-02-03 19:48 UTC, closed without merging