Updated scoring subsystem with backward movement
LakotaRobotics1038/2024RobotProject pull request #48
Opened 2024-01-30 22:26 UTC by matunkar

### Pull Request

---------------------------------------------

#### Issue Number

 Closes #41 

#### Comments

2024-01-30 23:34 UTC, matunkar reviewed
there is a reason the methods are like that

they're going to be changed to use constants but i dont want to do that until the operator joystick file is merged with main because thatll need to be updated too

2024-01-31 00:14 UTC, Griffin9881 approved these changes
I mean it looks like it would work i dont know if we want to do constants instead of passing a variable for run backwards but idk

2024-01-31 22:18 UTC, Gaviniscool17 submitted a review, later dismissed

2024-01-31 22:40 UTC, reediculous456 requested changes

2024-01-31 22:40 UTC, reediculous456 commented on src/main/java/frc/robot/constants/ScoringConstants.java
> +    public static final double zeroSpeed = 0;
```suggestion
    public static final double reverseMaxSpeed = 0;
```

2024-02-06 00:38 UTC, closed without merging