Score in Amp Auton
LakotaRobotics1038/2024RobotProject pull request #72
Opened 2024-02-08 00:57 UTC by ChasingCode34

### Pull Request

---------------------------------------------

#### Issue Number

#### Comments

2024-02-09 01:40 UTC, reediculous456 requested changes

2024-02-09 01:40 UTC, reediculous456 commented on src/main/java/frc/robot/autons/ScoreInAmp.java
> +                        new DriveVisionCommand(4)),
What is 4? If this is a vision target, you should pass an enum from Vision Targets instead of int

2024-02-09 01:40 UTC, reediculous456 commented on src/main/java/frc/robot/autons/ScoreInAmp.java
> +        PathPlannerPath pathToAmp = PathPlannerPath.fromPathFile(getName());
What is getName?

2024-02-10 15:46 UTC, SpecialSpark submitted a review, later dismissed
The changes Wes wanted have been addressed sending back up to Mentor Review

2024-02-10 15:55 UTC, reediculous456 requested changes

2024-02-10 15:55 UTC, reediculous456 commented on src/main/java/frc/robot/autons/ScoreInAmp.java
> +                                new DriveVisionCommand(VisionTarget.APT4.getValue()),
I think the drive vision command constructor should be modified to take in the enum instead of an int. The. You don’t need getvalue here

2024-02-10 15:56 UTC, reediculous456 commented
Also code is not compiling

2024-02-10 17:13 UTC, reediculous456 approved these changes

2024-02-10 17:13 UTC, merged