joystick code updated to current commands
LakotaRobotics1038/2024RobotProject pull request #80
Opened 2024-02-15 00:38 UTC by matunkar

### Pull Request

---------------------------------------------

#### Issue Number

Closes #23 
Closes #77 

#### Comments

2024-02-18 18:46 UTC, SpecialSpark approved these changes
I have no qualms with the code and it should run.

2024-02-19 02:23 UTC, reediculous456 requested changes

2024-02-19 02:23 UTC, reediculous456 commented on src/main/java/frc/robot/DriverJoystick.java
> +        rightTrigger.onTrue(new LiftDepressCommand());
Shouldn't these be wile true? that way if they let go of the button the command will end.
With onTrue, the command won't end until isFinished returns true

2024-02-19 02:23 UTC, reediculous456 commented on src/main/java/frc/robot/OperatorJoystick.java
> +        leftTrigger.onTrue(new ShootNoteCommand());
Same here, I think you want while true

2024-02-21 00:22 UTC, matunkar commented on src/main/java/frc/robot/DriverJoystick.java
> +        leftTrigger.onTrue(new LiftExtendCommand());
```suggestion
        leftTrigger.whileTrue(new LiftExtendCommand());
```

2024-02-21 00:22 UTC, matunkar commented on src/main/java/frc/robot/DriverJoystick.java
> +        rightTrigger.onTrue(new LiftDepressCommand());
```suggestion
        rightTrigger.whileTrue(new LiftDepressCommand());
```

2024-02-21 00:22 UTC, matunkar commented on src/main/java/frc/robot/OperatorJoystick.java
> +        rightTrigger.onTrue(new ScoreNoteAmpCommand());
```suggestion
        rightTrigger.whileTrue(new ScoreNoteAmpCommand());
```

2024-02-21 00:22 UTC, matunkar commented on src/main/java/frc/robot/OperatorJoystick.java
> +        leftTrigger.onTrue(new ShootNoteCommand());
```suggestion
        leftTrigger.whileTrue(new ShootNoteCommand());
```

2024-02-22 22:56 UTC, LandisCrawford6114 approved these changes

2024-02-22 22:56 UTC, merged